def build(bld):
    obj = bld(features='cxx cxxshlib')
    obj.name = 'libleqm-nrt'
    obj.target = 'leqm-nrt'
    obj.export_includes = ['.']
    obj.source = 'leqm-nrt.cc'

    obj = bld(features='cxx cxxprogram')
    obj.name = 'leqm-nrt-cli'
    obj.target = 'leqm-nrt'
    obj.source = 'leqm-nrt-cli.cc'
    obj.use = 'libleqm-nrt'
    obj.uselib = 'SNDFILE'

    bld.install_files('${PREFIX}/include', 'leqm-nrt.h')

